### ISSUE TITLE
Surefire fails

### ISSUE THREAD

**Issue by sasoria** [unitsofmeasurement/indriya#159]
OS: MacOs Mojave 10.14.1
Jdk: java 11.0.1 2018-10-16 LTS, Oracle
Mvn: Apache Maven 3.5.4

Running mvn clean install gives the following error: 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
	at org.jacoco.agent.rt.internal_c13123e.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_c13123e.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1:  9816 Abort trap: 6           /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java -javaagent:/Users/user/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/Users/user/git/indriya/target/jacoco.exec -jar /Users/user/git/indriya/target/surefire/surefirebooter5090949840585415283.jar /Users/user/git/indriya/target/surefire/surefire11967537843640693735tmp /Users/user/git/indriya/target/surefire/surefire_03978803293168558867tmp
```

I see that maven compiler plugin is configured for java 9. Are there any version dependencies?

**Comment by keilw** [comment]
Unlike the API which also uses multi-release-JAR features to support all Java versions at least from 8 onward, there is currently no version restriction. I can't see any problem like this in the CI instance:
https://circleci.com/gh/unitsofmeasurement/indriya/880
Nor ever faced it locally. I am pretty certain, it could be an incompatibility Java 11 introduced for Jacoco or the Maven plugin. Did you try using Java 9 (which the CI also does) or 10 instead?

**Comment by Daniel-Dos** [comment]
HI @keilw  and @sasoria 

with Java 11 really apresent this error, but using Java 10 pass  good.

**Comment by Daniel-Dos** [comment]
Hi, 

if update the plugin of jacoco to` <jacoco.version>0.8.2</jacoco.version>`, the build pass .

but some errors with javadocs during the build .

see log  .

[logs.txt](https://github.com/unitsofmeasurement/indriya/files/2545517/logs.txt)

**Comment by keilw** [comment]
Hi,
Thanks, does the 0.8.2 plugin version work including Java 11?
I think the warnings (the build does not break) are mostly from Javadoc being a little more picky with new Java versions about all the necessary tags. It could be a good idea to create a separate issue for the Javadoc improvements.

**Comment by Daniel-Dos** [comment]
Hi,
yes work with Java 9,10 and 11 . 

but will have problem with JavaDoc with Java 9,10 and 11 according to the log.

I send a PR to update the jacoco.

**Comment by keilw** [comment]
Can this be closed now?

**Comment by keilw** [comment]
There have  been fixes in unit-api, is there anything missing here?

**Comment by Daniel-Dos** [comment]
Hi @keilw ,

you can close the issue.

she worked here with JDK 11 .

but at least here for me is failing in Failed to execute goal com.mycila: license-maven-plugin: 3.0: check

**Comment by keilw** [comment]
Great thanks
