### ISSUE TITLE
AbstractError when migrating to ServiceProvider.getFormatService() instead of getUnitFormatService() 

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/indriya#231]
I've updated to indyria 2.0-PRD, and I've noticed that `getUnitFormatService()` was deprecated, in favour of `getFormatService()`. 

However when doing that I get NullPointerException() coming from within `getformatService()`. 

Here my code, where a load all possible service providers to use them later for parsing: 
```
for (ServiceProvider provider : ServiceProvider.available()) {
            UnitFormatService formatService = provider.getFormatService();

            final String providerName = provider.getClass().getName();
            unitFormats.put(providerName, formatService.getUnitFormat());
        }
```

I get 
```java.lang.AbstractMethodError: javax.measure.spi.ServiceProvider.getFormatService()Ljavax/measure/spi/FormatService;```

My dependencies are: 

```
    compile 'tech.units:indriya:2.0-EDR'
    compile group: 'si.uom', name: 'si-units-java8', version: '1.2'
    compile group: 'si.uom', name: 'si-quantity', version: '1.2'
```

we've discussed already in the past but I could not find the issue. 

Thank you in advance.

**Comment by keilw** [comment]
You cannot use `si-units-java8` (which is in fact based on a completely **different** implementation, uom-se !) or `si-quantity` in version 1.2 with Indriya 2.0. If you want to use uom-se, you can find it [here](https://github.com/unitsofmeasurement/uom-se), but it won't implement JSR 385. 
The correct combination for Indriya 2 would be the 2.0-SNAPSHOT releases of these libraries, otherwise please use Indriya 1.x, currently 1.3 as seen in the [dependencies of si-units](https://search.maven.org/artifact/si.uom/si-parent/1.2/jar). 
If you want to use Indriya, please make sure it's `si-units` without the "java8", that is a legacy version we no longer maintain after 2.0.
Sorry for the confusion, but compared to a whole new major version of the JDK every 6 months I guess that still isn't so bad ;-)

**Comment by lfoppiano** [comment]
@keilw what about the version `2.0-PRD`?

**Comment by lfoppiano** [comment]
Thank you!

**Comment by lfoppiano** [comment]
Thank you @keilw !

So now I have 

```
    compile 'tech.units:indriya:2.0-PRD'
    compile group: 'si.uom', name: 'si-units', version: '2.0-SNAPSHOT'
    compile group: 'si.uom', name: 'si-quantity', version: '2.0-SNAPSHOT'
```

Should I also add all the systems libraries (version 2.0-SNAPSHOT), like: 

```
//    compile group: 'systems.uom', name: 'systems-quantity', version: '1.0'
//    compile group: 'systems.uom', name: 'systems-ucum-java8', version: '1.0'
//    compile group: 'systems.uom', name: 'systems-unicode-java8', version: '1.0'
//    compile group: 'systems.uom', name: 'systems-common', version: '1.0'
//    compile group: 'systems.uom', name: 'systems-unicode', version: '1.0'
//    compile group: 'systems.uom', name: 'systems-ucum', version: '1.0'
```

Also, the `-java8` should be ignored as well in this case?

**Comment by lfoppiano** [comment]
Again me, 
   so if I use these versions: 
```
    compile 'tech.units:indriya:2.0-PRD'
    compile group: 'si.uom', name: 'si-units', version: '2.0-SNAPSHOT'
    compile group: 'si.uom', name: 'si-quantity', version: '2.0-SNAPSHOT'
```

I need to build `si-units` 2.0-SNAPSHOT, when I try to do so, I get a problem with a test: 

```
[ERROR] /Users/lfoppiano/development/projects/uom/si-units/units/src/test/java/si/uom/PrefixTest.java:[87,47] no suitable method found for of(double,double)
    method tech.units.indriya.function.RationalConverter.of(java.math.BigInteger,java.math.BigInteger) is not applicable
      (argument mismatch; double cannot be converted to java.math.BigInteger)
    method tech.units.indriya.function.RationalConverter.of(long,long) is not applicable
      (argument mismatch; possible lossy conversion from double to long)
```

The problem is that this version `2.0-SNAPSHOT` is using indyra 2.0-SNAPSHOT... so should I use directly that version? 

I'm not sure I've understood which versions to use with indyra 2.0-PRD.. 

Thank you

**Comment by keilw** [comment]
I'm afraid, you need to use indriya 2.0-SNAPSHOT. @andi-huber and a few others hav done a bit of improvement under the hood, so especially the whole RationalConverter changed in the last weeks. It it advisable to use the Snapshot builds here until all go Final (https://jcp.org/en/jsr/detail?id=385 shows, the Public Review Final Approval Ballot is still pending)

**Comment by andi-huber** [comment]
You might be interested in having a look at jitpack [1]. It eg. allows to build against the latest commit of the master branch.

[1] https://jitpack.io/#unitsofmeasurement/indriya

**Comment by keilw** [comment]
That's good to know, thanks. Every snapshot build also gets deployed to JFrog/Bintray.

**Comment by lfoppiano** [comment]
@keilw do I need any special configuration for getting the snapshots from Bintray? Here I don't see any snapshots: https://bintray.com/unitsofmeasurement/maven 

@andi-huber on jitpack are there also other libraries from unitsofmeasurement?

**Comment by lfoppiano** [comment]
I've built in local version 2.0-SNAPSHOT of indriya, si-unit and si-quantities (I had to disable tests on the former - see related ticket in si-units). What else do I need? 

I cannot build uom-systems...  see related ticket...

**Comment by lfoppiano** [comment]
Me again... So after trial and error on several combination I finally reach a sort of stable combination of libraries.. although I would like to use the version 2.0-SNAPSHOT (once i manage to build it). 

Here my dependencies: 

```
    compile 'tech.units:indriya:1.3'
    compile group: 'si.uom', name: 'si-units', version: '1.2'
    compile group: 'si.uom', name: 'si-quantity', version: '1.2'
    compile group: 'systems.uom', name: 'systems-quantity', version: '1.0'
    compile group: 'systems.uom', name: 'systems-common', version: '1.0'
    compile group: 'systems.uom', name: 'systems-unicode', version: '1.0'
    compile group: 'systems.uom', name: 'systems-ucum', version: '1.0'
```

I don't use system-xy-java8, is it correct to do so? 



Anyway at initialisation I have this error: 

```
Jun 14, 2019 1:58:50 PM tech.units.indriya.format.SymbolMap <init>
SEVERE: Error
java.lang.ClassNotFoundException: tec.units.indriya.unit.Units
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at tech.units.indriya.format.SymbolMap.<init>(SymbolMap.java:116)
	at tech.units.indriya.format.SymbolMap.of(SymbolMap.java:143)
	at systems.uom.ucum.format.UCUMFormat$Print.<clinit>(UCUMFormat.java:360)
	at systems.uom.ucum.format.UCUMFormat.getInstance(UCUMFormat.java:105)
	at systems.uom.ucum.internal.UCUMFormatService.<init>(UCUMFormatService.java:59)
	at systems.uom.ucum.internal.UCUMServiceProvider.getUnitFormatService(UCUMServiceProvider.java:57)
	at org.grobid.core.data.normalization.QuantityNormalizer.<init>(QuantityNormalizer.java:52)
	at org.grobid.core.engines.QuantityParser.<init>(QuantityParser.java:48)
	at org.grobid.core.engines.QuantityParser.getNewInstance(QuantityParser.java:67)
	at org.grobid.core.engines.QuantityParser.getInstance(QuantityParser.java:54)
	at org.grobid.core.engines.QuantityParserIntegrationTests.setUp(QuantityParserIntegrationTests.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

which is thrown at this point: 

```
 UnitFormatService formatService = provider.getUnitFormatService();
```

If you see the complete code in my first comment, however now, if I use `getFormatService()`, I will get this error: 
```
Caused by: java.lang.AbstractMethodError: Receiver class systems.uom.common.internal.CommonServiceProvider does not define or inherit an implementation of the resolved method abstract getFormatService()Ljavax/measure/spi/FormatService; of abstract class javax.measure.spi.ServiceProvider.
```

Any advice? 

Thank you in advance

**Comment by keilw** [comment]
You cannot use getFormatService if you go back to the 1.x versions. That is clear, the other problem is some earlier version of Indriya accidentially referenced. I suppose in one of the other Systems, because SI Units has undergone more work when the Metric System was redefined. Could you try the 1.1-SNAPSHOT of uom-systems? If that still shows the problem we'll redeploy that. Thank you for your patience and help.

**Comment by lfoppiano** [comment]
@keilw thanks for your help. I'm checking right away.  Should I also include the `-java8` libraries of `uom-systems`?

**Comment by lfoppiano** [comment]
@keilw where should I get the 1.1-SNAPSHOT? as I mentioned https://github.com/unitsofmeasurement/indriya/issues/231#issuecomment-501908538 I'm not finding any snapshot in bintray actually.

**Comment by lfoppiano** [comment]
Another test I've done, I've managed to build everything 2.0-SNAPSHOT (with si-units and si-quantity, from @andi-huber). I have tried uom-system 1.1-SNAPSHOT but it was not found, so I use the 2.0-SNAPSHOT: 

```
    compile 'tech.units:indriya:2.0-SNAPSHOT'
    compile group: 'si.uom', name: 'si-units', version: '2.0-SNAPSHOT'
    compile group: 'si.uom', name: 'si-quantity', version: '2.0-SNAPSHOT'
    compile group: 'systems.uom', name: 'systems-quantity', version: '2.0-SNAPSHOT'
    compile group: 'systems.uom', name: 'systems-common', version: '2.0-SNAPSHOT'
    compile group: 'systems.uom', name: 'systems-unicode', version: '2.0-SNAPSHOT'
    compile group: 'systems.uom', name: 'systems-ucum', version: '2.0-SNAPSHOT'
```

the result is still failing on `ServiceProvider.available()` call: 

 ```
Caused by: java.lang.NoClassDefFoundError: tech/units/indriya/spi/DefaultServiceProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at javax.measure.spi.ServiceProvider.available(ServiceProvider.java:266)
	[...]
Caused by: java.lang.ClassNotFoundException: tech.units.indriya.spi.DefaultServiceProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more
```

What abotu the https://github.com/unitsofmeasurement/indriya/issues/231#issuecomment-502000234?

**Comment by keilw** [comment]
Issue moved to [unitsofmeasurement/uom-systems #142](https://github.com/unitsofmeasurement/uom-systems/issues/142) via [**ZenHub**](https://www.zenhub.com/)
