### ISSUE TITLE
Static piCache hash map is not thread-safe

### ISSUE THREAD

**Issue by stefanuhrig** [unitsofmeasurement/indriya#371]
Hi all,

If you have two threads and each thread has its own local `UnitConverter` instance, a concurrent call of `#convert()` can lead to a `ConcurrentModificationException` because access to the static `Calculus$Pi#piCache` variable is not synchronized: https://github.com/unitsofmeasurement/indriya/blob/b8e58ca04913c858038217e7c32bc9d26798518f/src/main/java/tech/units/indriya/function/Calculus.java#L150

This is a stack trace showing the issue:

```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
	at tech.units.indriya.function.Calculus$Pi.ofNumDigits(Calculus.java:150)
	at tech.units.indriya.function.PowerOfPiConverter.getValue(PowerOfPiConverter.java:125)
	at tech.units.indriya.function.PowerOfPiConverter.getValue(PowerOfPiConverter.java:48)
	at tech.units.indriya.function.MultiplyConverter.getFactor(MultiplyConverter.java:242)
	at tech.units.indriya.function.PowerOfPiConverter.convertWhenNotIdentity(PowerOfPiConverter.java:100)
	at tech.units.indriya.function.AbstractConverter$Pair.convertWhenNotIdentity(AbstractConverter.java:398)
	at tech.units.indriya.function.AbstractConverter.convert(AbstractConverter.java:221)
```

If you have further questions on the issue, please reach out.

Cheers,
Stefan

**Comment by keilw** [comment]
Any suggestion or PR? 
@andi-huber, thoughts on that or an easy way to improve?

**Comment by stefanuhrig** [comment]
Well, a quick-fix would be switching from `HashMap` to `Hashtable` because `Hashtable` is synchronized by default. I can prepare a PR if you like. However, I'm not very familiar with the project, and there might be other occurrences of static unsynchronized cache variables.

**Comment by keilw** [comment]
While the JDK may never seriously remove Hashtable, I guess a slightly cleaner approach could be one of those: https://crunchify.com/hashmap-vs-concurrenthashmap-vs-synchronizedmap-how-a-hashmap-can-be-synchronized-in-java/

**Comment by stefanuhrig** [comment]
`ConcurrentHashMap` seems like a good choice to me because read operations won't block.

**Comment by stefanuhrig** [comment]
I've opened PR #372 for the issue.

**Comment by andi-huber** [comment]
I have merged a fix for Pi.

**Comment by stefanuhrig** [comment]
Thanks for fixing this so quickly!
